version: 2.1


orbs:
  python: circleci/python@1.1.0
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/uvicorn.txt
      - run:
          command: |
            mkdir test-results
            python -m pytest
          name: Test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: reports
      - codecov/upload:
          file: test-reports/coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
